[project]
name = "datarpg"
version = "1.0.0"
description = "Default template for PDM package"
authors = [
    {name = "Giorgio Vilardo", email = "giorgio@vilardo.eu"},
]
dependencies = []
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
